### PR TITLE
Add lm-eval-service controller

### PR DESCRIPTION
**Pull request by yhwang**
refactor the existing TrustyAIService controller and add the LMEvalService controller

### CODE REVIEW

**Comment by ruivieira** [comment]
Thanks @yhwang, this is brilliant!

Just some notes:

- There seems to be a build [issue](https://github.com/trustyai-explainability/trustyai-service-operator/actions/runs/10052557052/job/27848065438?pr=258#step:5:40) with the `slices` package
- I've created a issue label `lm-eval` to track issues related to this project
- There is a [milestone](https://github.com/trustyai-explainability/trustyai-service-operator/milestone/16) and[ project tab](https://github.com/orgs/trustyai-explainability/projects/12/views/26) too

I'm fine with merging as it is, so that we have a baseline on the dev branch and we can work from there, if you prefer to fix any issues in future PRs.

**Comment by yhwang** [comment]
@ruivieira thanks for the review

> There seems to be a build [issue](https://github.com/trustyai-explainability/trustyai-service-operator/actions/runs/10052557052/job/27848065438?pr=258#step:5:40) with the slices package

I just updated the workflow of the GH action to use newer version of go. That should solve the issue.

**Comment by yhwang** [comment]
The support of using secrets as files or env vars was landed on the fms-lm-eval-service repo. So I quickly added them here too. If the build passes, I am good to merge this too.

**Review by ruivieira — APPROVED** [review]

**Comment by yhwang** [comment]
have the last change to update the yaml linter config and fix the errors from the linter GH action. I think it's ready for merge!

**Pull request merged**
